import {test,expect,Page} from '@playwright/test';
const base='http://127.0.0.1:3000';
async function registerAndOnboard(page:Page,prefix:string){await page.goto(base);await page.getByRole('button',{name:/English/}).click();await page.getByRole('button',{name:'Create account'}).click();await page.getByLabel('Name').fill(prefix);await page.getByLabel('Email').fill(`${prefix.replaceAll(' ','').toLowerCase()}-${Date.now()}@example.com`);await page.getByLabel('Password').fill('VeryStrong123!');await page.getByRole('button',{name:'Register'}).click();await expect(page.getByText('First, tell us about yourself')).toBeVisible();await page.getByPlaceholder('e.g. Ahmed').fill(prefix);const next=page.getByRole('button',{name:'Continue'});await next.click();await page.getByLabel('Monthly income').fill('45000');await page.getByLabel('Monthly expenses').fill('24000');await next.click();await next.click();await page.getByRole('button',{name:'Open my dashboard'}).click();await expect(page.getByText(`Good morning, ${prefix}`)).toBeVisible()}

test('language gate precedes secure authentication and Arabic applies globally',async({page})=>{await page.goto(base);await expect(page.getByText('Choose your language')).toBeVisible();await page.getByRole('button',{name:/العربية/}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.getByText('مرحبًا بعودتك')).toBeVisible();await expect(page.getByRole('button',{name:'إنشاء حساب'})).toBeVisible()});

test('registration, onboarding, server persistence, budget and reports',async({page})=>{test.setTimeout(120000);await registerAndOnboard(page,'Mona Test');await page.locator('nav').getByRole('button',{name:'Transactions'}).click();await page.getByRole('button',{name:'Add transaction'}).click();await page.locator('.transactionFields input[type="number"]').fill('1500');await page.getByPlaceholder('e.g. Business lunch').fill('Groceries');await page.getByRole('button',{name:'Save transaction'}).click();await expect(page.locator('.transactionTable')).toContainText('Groceries');await page.reload();await page.locator('nav').getByRole('button',{name:'Transactions'}).click();await expect(page.locator('.transactionTable')).toContainText('Groceries');const keys=await page.evaluate(()=>Object.keys(localStorage));expect(keys.filter(k=>/transaction|budget|goal|profile|report|alert|ai-history/.test(k))).toEqual([]);await page.locator('nav').getByRole('button',{name:'Budget'}).click();await page.locator('.budgetInput input').first().fill('12000');await page.getByRole('button',{name:/Save plan/}).click();await expect(page.getByRole('button',{name:/Saved/})).toBeVisible();await page.locator('nav').getByRole('button',{name:'Reports'}).click();await page.locator('.proReport').first().getByRole('button',{name:'Preview'}).click();await expect(page.locator('.reportPreviewPanel iframe')).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:/Download/}).click();expect((await download).suggestedFilename()).toContain('report.html')});

test('Monte Carlo, goals, portfolio empty states, and honest ML unavailability',async({page})=>{test.setTimeout(120000);await registerAndOnboard(page,'Nour Test');await page.locator('nav').getByRole('button',{name:'Simulator'}).click();await page.getByRole('button',{name:/Run 10,000 paths/}).click();await expect(page.getByText('Median P50')).toBeVisible();await page.locator('nav').getByRole('button',{name:'Goals'}).click();await expect(page.getByText('No goals yet')).toBeVisible();await page.locator('nav').getByRole('button',{name:'Portfolio'}).click();await expect(page.getByText(/Record your first portfolio/)).toBeVisible();await page.locator('nav').getByRole('button',{name:'Insights'}).click();await expect(page.getByText('ML unavailable')).toBeVisible()});

test('AI mutation requires exact server confirmation token',async({page})=>{test.setTimeout(120000);await registerAndOnboard(page,'Ali Test');await page.route('**/api/advisor',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({answer:'I can update your employment status.',actions:[{type:'update_profile',label:'Update employment',reason:'Keep profile current',payload:{employment:'Self-employed'}}],memory:'postgres',model:'test'})}));await page.getByRole('button',{name:/Ask AI/}).click();const input=page.getByPlaceholder('Ask about your money…');await input.fill('Update employment');await input.press('Enter');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Review & apply'}).click();await expect(page.getByRole('button',{name:'Applied'})).toBeDisabled()});
